export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAILURE = 'FETCH_INGREDIENTS_FAILURE';

export const ORDER_BURGER_BEGIN = 'ORDER_BURGER_BEGIN';
export const ORDER_BURGER_SUCCESS = 'ORDER_BURGER_SUCCESS';
export const ORDER_BURGER_FAILURE = 'ORDER_BURGER_FAILURE';
